# Generated by Django 3.2 on 2023-03-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='myWins',
            field=models.TextField(blank=True),
        ),
    ]
