# Generated by Django 3.2 on 2023-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_mywins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='myWins',
        ),
        migrations.AddField(
            model_name='bids',
            name='biduserid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bids',
            name='myWins',
            field=models.TextField(blank=True),
        ),
    ]
